# web server config
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


# data source config
spring:
  application:
    name: tweets-snowflake-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # HikariCP data source framework
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql driver for mysql 8
    hikari:
      connection-timeout: 30000             # timeout for waiting for a connection from the pool (milliseconds)
      minimum-idle: 5                       # minimum number of idle connections
      maximum-pool-size: 20                 # maximum number of connections
      auto-commit: true                     # automatically commit statements
      idle-timeout: 600000                  # maximum time a connection can be idle before being closed (milliseconds)
      pool-name: DateSourceHikariCP         # name of the connection pool
      max-lifetime: 1800000                 # maximum lifetime of a connection (milliseconds)
      connection-test-query: SELECT 1       # test query to validate a connection

# snowflake id generator config
# sum of bits of each part must <= 23 bits
snowflake:
  machineId: 2
  datacenterId: 1
  sequenceBit: 10
  machineBit: 10
  datacenterBit: 2