# web server config
server:
  port: 21000

spring:
  datasource:
    url: jdbc:mysql://192.168.83.144:3306/tiny-twitter-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
